#!/bin/bash

# Verifies that modules contain README files with required sections:
# Introduction, Requirements, Installation, and Configuration.

function usage() {
  cat <<EOF
Check modules for README files.

 Usage: $(basename "$0") path

Arguments:
 path: may be a specific module directory or a directory containing modules.
EOF
}

function readme_check() {
    SUCCESS=0
    FILENAME="$1/README.md"

    if [ ! -f $FILENAME ]
    then
        echo "$FILENAME doesn't exist"
        return 1
    fi

    if ! grep -q "Introduction" $FILENAME
    then
        echo "$FILENAME doesn't contain an introduction"
        SUCCESS=1
    fi

    if ! grep -q "Requirements" $FILENAME
    then
        echo "$FILENAME doesn't contain requirements"
        SUCCESS=1
    fi

    if ! grep -q "Installation" $FILENAME
    then
        echo "$FILENAME doesn't contain installation instructions"
        SUCCESS=1
    fi

    if ! grep -q "Configuration" $FILENAME
    then
        echo "$FILENAME doesn't contain configuration instructions"
        SUCCESS=1
    fi

    return $SUCCESS
}

EXIT_STATUS=0

if [[ -z "$1" ]]; then
  usage
  exit 1
fi

entries=()
basename=$(basename "$1")
module_file="$1/${basename}.module"
if [[ -f "${module_file}" ]]; then
  entries+=("$1")
else
  entries=("${1%/}"/*)
fi

for entry in ${entries[*]}
do
    if [ -d $entry ]
    then
        if ! readme_check "$entry"
        then
            EXIT_STATUS=1
        fi
    fi
done

exit $EXIT_STATUS
